[package]
name = "constellation-cxx"
version = "0.1.0"
edition = "2021"

[dependencies]
star-constellation = { git = "https://github.com/brave/constellation", rev = "c33e740c46062060b86e30504bca07147c6da5b8" }
cxx = "1.0"

[lib]
name = "constellation_cxx"
crate-type = ["rlib"]
